### ISSUE TITLE
Cannot install p5bots-server on MacOSX

### ISSUE THREAD

**Issue by jvouillon** [sarahgp/p5bots#10]
Hi, trying to install p5bots-server on MacOSX 10.11.2. Got this error:

"Failed at the serialport@1.7.4 install script 'node-pre-gyp install --fallback-to-build'.
Make sure you have the latest version of node.js and npm installed.
If you do, this is most likely a problem with the serial port package..."

Node and npm are up to date. 
Is there a way to fix that problem or am I missing something?

Thanks.

**Comment by sarahgp** [comment]
It's probably code on my end that needs to be updated. I'll be able to look
at it this weekend but not before then.

**Comment by jvouillon** [comment]
No rush! :-)
Thanks!

**Comment by benIflock** [comment]
hi
i am also struggling to install the package with npm on a mac with the same error as above

is there anyway to install manually?

thanks

b

**Comment by sarahgp** [comment]
Yes, you can download this repo, `cd` into the `p5bots-server` directory, `npm install` and then run the `app.js` file. This may still result in the serialport error, however; I think there is a version conflict.

Can you let me know @benIflock & @jvouillon your npm & node versions?

Fixing this is still totally on my list, but grad school is eating my brain a little. If you resolve the conflict before I get to it, please feel free to open a PR.

**Comment by jvouillon** [comment]
Hi, my versions are:
node -v v5.4.1
npm -v 3.5.3

**Comment by benIflock** [comment]
hi - thanks for that 

yeah got the same error with the serialport - i'm running 
npm 2.14.12 and  node v4.2.6

will have a dig around see if i can find a solution....

**Comment by sarahgp** [comment]
I suspect it is because your node is up-to-date and the older version of serialport is choking on it. Do one of you want to update serialport and see if that fixes things?

**Comment by benIflock** [comment]
i managed to get everything running with latest version of serialport and using limzykenneth's fork from a couple of days ago
thanks 

b

**Comment by limzykenneth** [comment]
@benIflock Cheers. I made it a bit easier to use my fork by separating out `p5bots-server` into its own repo so in `package.json` you can simply add 

```
"p5bots-server": "git+https://github.com/limzykenneth/p5bots-server.git"
```

to the dependencies and `npm install`.
