### ISSUE TITLE
Unable to write to RGB LED

### ISSUE THREAD

**Issue by redspiderfish** [sarahgp/p5bots#15]
I can't seem to write the color to the RGB LED. Error as per screenshot: 

<img width="583" alt="screen shot 2016-10-18 at 1 03 27 am" src="https://cloud.githubusercontent.com/assets/1276932/19447169/da70fd98-94ce-11e6-8715-326e7c6e6c90.png">

<img width="326" alt="screen shot 2016-10-18 at 1 03 48 am" src="https://cloud.githubusercontent.com/assets/1276932/19447176/e2e8c122-94ce-11e6-8eaf-9354cf673140.png">

**Comment by sarahgp** [comment]
Can you try it with the version of p5bots linked in #14 and let me know if that fixes it? (Replace the client-side script with the one in the gist.)

**Comment by sarahgp** [comment]
This has been updated with the new version. To fix, download new client script from t[he lib directory](https://github.com/sarahgp/p5bots/tree/master/lib).

**Comment by scenaristeur** [comment]
got the same issue with 
/*! p5.js v0.5.6 January 03, 2017 */
and 
/*! p5bots.js v0.3.2 January 02, 2017 */
