### ISSUE TITLE
Trouble running helloWorld. Receiving message - 1: Uncaught ReferenceError: p5 is not defined

### ISSUE THREAD

**Issue by mrbombmusic** [sarahgp/p5bots#17]
Hi, I might be way in over my head here, but I am trying to run p5.bots in p5.js. I followed all the directions in the helloWorld tutorial and everything seems to be in the right place, but when I run the sketch, I get this message in the console - 1: Uncaught ReferenceError: p5 is not defined

I feel like I am doing everything. All the terminal message worked although maybe I am not making the files correctly or in the right place. The local host address is 3000, not 8000 like the tutorial says.

I have basic computer literacy skills so I am a bit at a loss outside of the tutorial. Any help would be appreciated.

Thanks

**Comment by TomYeoman** [comment]
Sounds like the required p5 libraries haven't been loading correctly. Is your terminal reporting any js files aren't being loaded?

npm install
npm start
Open localhost:8000

Works fine for me on installs (Windows 10, node

**Comment by sarahghp** [comment]
Gonna close this up. Thanks @TomYeoman for your suggestions. In general the issues here are probably not the best place to get basic help, just because I don't have much time for open source these days. 😞

**Comment by TomYeoman** [comment]
No problem @sarahgp thanks for your contributions :)
