### ISSUE TITLE
pin.blink increment

### ISSUE THREAD

**Issue by naimenz** [sarahgp/p5bots#20]
I think I may have spotted an issue with led blinking.
In the pin.blink function, the blinkCounter is incremented AFTER sending the id with the current blinkCounter. This means that when pin.noBlink() is called, the id it gets is one greater than the id of the blinking led. For some reason it still worked the first time you turned the blinking on/off, but after that it wouldn't work. Simply moving the increment to before the function fixed it for me. I hope this helps :)

**Comment by sarahgp** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212618-315916292_1-s4-v1.png?transparent=1&palette=1&width=246)

Thanks for noticing that one.
