### ISSUE TITLE
bots-go requirs -d option even if I am in helloWorld. (Windows 10)

### ISSUE THREAD

**Issue by KouichiMatsuda** [sarahgp/p5bots#3]
I am using ps.bots.js on Windows. It's very interesting!

According to reference (https://github.com/sarahgp/p5bots/blob/master/examples/HelloWorld.md), 
I returned to the Terminal. I was in helloWorld and then typed the following;

`bots-go -f /Users/computer/sites/p5bots/helloWord/index.html`

After opening a web browser, I types "localhost:8000"
The Chrome browser failed to get p5.js and other JavaScript stuffs, and then showed the error in the console.
x GET http://localhost:8000/libraries/p5.js 
x GET http://localhost:8000/libraries/p5.dom.js 
x GET http://localhost:8000/libraries/p5.sound.js 
x GET http://localhost:8000/libraries/p5bots.js 
x GET http://localhost:8000/sketch.js  

But it works well when I appened "-d ./".

`bots-go -f /Users/computer/sites/p5bots/helloWord/index.html -d ./`

Is -d required in Windows 10? Unfortunately I don't have Mac. 
Am I missing something?

**Comment by sarahgp** [comment]
You are not missing anything; it is an error on my part. I'll fix it in the next few days. Thank you for finding it!

**Comment by KouichiMatsuda** [comment]
Thanks!

**Comment by largocreatura** [comment]
yes, "-d ./" is neccesary on mac too. Thanks!

**Comment by sarahgp** [comment]
I've updated the instruction to just use the `-d` flag, since the `-f` flag is more properly used for filenames other than `index.html`.
