### ISSUE TITLE
in rare cases, serial initial reads/writes may be lost

### ISSUE THREAD

**Issue by daverusso** [sarahgp/p5bots#6]
In rare cases serial reads/writes may be lost at startup due to typo bug:  in serial.js `serialDispatch()` the line:
> `serialport.isOpen ?`

should be

> `serialport.isOpen() ?`

Since `isOpen` is a function, the test is always true, even if the serial port isn't really open.  As a result, `serialDispatch()` never queues reads/writes

**Comment by sarahgp** [comment]
Closed via #8
