### ISSUE TITLE
it's not possible to use a client running on a different device than the server

### ISSUE THREAD

**Issue by daverusso** [sarahgp/p5bots#7]
In p5bots.js the connection to the server is made via the hard coded URL 'http://localhost:8000/sensors'.  If instead, it used the location of the server, clients can run _anywhere_ on the network running the server.

So, to fix this one simply needs to change the line in p5bots.js from 

> `var socket = io.connect('http://localhost:8000/sensors');`

to

> `var socket = io.connect(location.origin + '/sensors');`

**Comment by sarahgp** [comment]
Closed via #8.
